title: "GetPEC mbH – Thermische Messtechnik und thermodynamische Beratung"
description: "GetPEC entwickelt kundenspezifische Prüfstände, thermische Messtechnik und thermodynamische Analysen für Forschung, Entwicklung und industrielle Spezialanwendungen."
url: "https://axels83.github.io"
baseurl: "/GetPEC-public"
lang: de
author:
  name: GetPEC mbH
  email: info@getpec.de

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
